title: "Guide To Online Privacy"
author: "Ieuan Paynter"
description: "A simple guide to online privacy, designed to be easily read and understood by readers of all technical knowledge"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {title: "About", file: "About.html", icon: About}
  - {title: "Useful Tools", file: "useful.html"}
  - {title: "Blog", file: "blog.md"}

external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:16651243@students.southwales.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/SadWings"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
